language: minimal

dist: bionic

services:
  - docker

before_install:
  - git fetch origin master
  - git checkout master
  - docker build . -t ci

script:
  - docker run -e GH_PERSONAL_TOKEN="${GH_PERSONAL_TOKEN}" $BUILD_ID=${BUILD_ID} ci