language: minimal

dist: bionic

jobs:
  include:
    - stage: Build Dependency Image
      name: "Build the base Image"     
      script:
        - sudo apt update &> /dev/null
        - sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y &> /dev/null
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &> /dev/null
        - sudo apt install docker-ce docker-ce-cli containerd.io &> /dev/null
        - docker build -f Dockerfile.builder . -t baalajimaestro/uup_dumper:latest
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push baalajimaestro/uup_dumper
    - script:
        - sudo apt update &> /dev/null
        - sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y &> /dev/null
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &> /dev/null
        - sudo apt install docker-ce docker-ce-cli containerd.io &> /dev/null
        - docker build -f Dockerfile . -t ci:latest
        - docker run -e GH_PERSONAL_TOKEN="${GH_PERSONAL_TOKEN}" -e $BUILD_ID=${BUILD_ID} ci
      name: "Run the Build"